const schedule_data = [
	{
		id: "083101",
		topic: "Product Management",
		desc: "From Problem to Product, Defining the Right Solution",
		speaker: "Desi Purnamasari",
		date: "02",
		month: "Mei",
	},
	{
		id: "083102",
		topic: "UX Research",
		desc: "Empathize to Build, Uncovering User Needs",
		speaker: "Intan Pertiwi Sianipar",
		date: "08",
		month: "Mei",
	},
	{
		id: "083103",
		topic: "UI/UX Design + Remote Work Sharing Session",
		desc: "From Insight to Interface: Designing User Centered Solutions",
		speaker: "Laila Adila",
		date: "08",
		month: "Mei",
	},
	{
		id: "083104",
		topic: "UX Writing",
		desc: "Clarity in Every Tap, Writing for Best Experience",
		speaker: "Purna Anantha",
		date: "15",
		month: "Mei",
	},
	{
		id: "083105",
		topic: "Software Engineering + Remote Work Sharing Session",
		desc: "Turning Design into Reality, Bridging with Developers",
		speaker: "Alfred Soegiarto ",
		date: "16",
		month: "Mei",
	},
	{
		id: "083106",
		topic: "Mentoring & Portofolio Review Session",
		desc: "Elevate Your Story, Gain Feedback to Enhance Your Readiness",
		speaker: "Moh Riansyah",
		date: "22",
		month: "Mei",
	},
	{
		id: "083107",
		topic: "English Profesional & Public Speaking",
		desc: "Pitch and Present, Effective Communication in the Digital Workspace",
		speaker: "Nieza Ayurisma",
		date: "23",
		month: "Mei",
	},
	{
		id: "083108",
		topic: "Pitching Day & Virtual Games",
		desc: "",
		speaker: "Faris Rakha | Rayyan Adwiarto | Denny Wirawan",
		date: "30",
		month: "Mei",
	},
	{
		id: "083109",
		topic: "Career Guide & Mental Health Session",
		desc: "Thrive, Not Survive: Building a Sustainable Career Globally",
		speaker: "Mareda Fenty",
		date: "23",
		month: "Mei",
	},
];

export default schedule_data;