const schedule_data = [
	{
		id: "083101",
		day:"DAY 01",
		topic: "From Problem to Product, Defining the Right Solution",
		speaker: "Desi Purnamasari",
		speakerJob:"Product Director @StraitsX, Fazz Group",
		date: "02 Mei 2026",
		time: "09.00 - 12.00 WIB",
    	speakerPhoto: "/Assets/Revamp/Speaker/Speaker-Black-and-White/Desi-Purnamasari.png",
	},
	{
		id: "083102",
		day:"DAY 02",
		topic: "Empathize to Build, Uncovering User Needs",
		speaker: "Intan Pertiwi Sianipar",
		speakerJob:"Head of CX Research @Bank Raya",
		date: "08 Mei 2026",
		time: "19.00 - 21.00 WIB",
		speakerPhoto: "/Assets/Revamp/Speaker/Speaker-Black-and-White/Intan-Pertiwi.png",
	},
	{
		id: "083103",
		day:"DAY 03",
		topic: "From Insight to Interface: Designing User Centered Solutions",
		speaker: "Laila Adila",
		speakerJob: "Sr. UI/UX & Digital Designer @Chykalophia",
		date: "09 Mei 2026",
		time: "10.00 - 12.00 WIB",
		speakerPhoto: "/Assets/Revamp/Speaker/Speaker-Black-and-White/Laila-Adila.png",
	},
	{
		id: "083104",
		day: "DAY 04",
		topic: "Clarity in Every Tap, Writing for Best Experience",
		speaker: "Purna Anantha",
		speakerJob: "Lead UX Writer @Telkom Indonesia",
		date: "15 Mei 2026",
		time: "19.00 - 21.00 WIB",
		speakerPhoto: "/Assets/Revamp/Speaker/Speaker-Black-and-White/Purna-Anantha.png",
	},
	{
		id: "083105",
		day: "DAY 05",
		topic: "Turning Design into Reality, Bridging with Developers",
		speaker: "Alfred Soegiarto ",
		speakerJob: "Fullstack Engineer @codewithfred",
		date: "16 Mei 2026",
		time: "10.00 - 12.00 WIB",
		speakerPhoto: "/Assets/Revamp/Speaker/Speaker-Black-and-White/Alfred-Soegiarto.png",
	},
	{
		id: "083106",
		day: "DAY 06",
		topic: "Elevate Your Story, Gain Feedback to Enhance Your Readiness",
		speaker: "Moh Riansyah",
		speakerJob: "Product Design Manager @Deltadata Mandiri",
		date: "22 Mei 2026",
		time: "19.00 - 21.00 WIB",
		speakerPhoto: "/Assets/Revamp/Speaker/Speaker-Black-and-White/Moh-Riansyah.png",
	},
	{
		id: "083107",
		day: "DAY 07",
		topic: "Pitch and Present, Effective Communication in the Digital Workspace",
		speaker: "Nieza Ayurisma",
		speakerJob: "TOEFL iBT/ITP & ESP Specialist @Dibimbing.id",
		date: "23 Mei 2026",
		time: "10.00 - 12.00 WIB",
		speakerPhoto: "/Assets/Revamp/Speaker/Speaker-Black-and-White/Nieza-Ayurisma.png",
	},
	{
		id: "083108",
		day: "DAY 08",
		topic: "Pitching Day & Virtual Games",
		speaker: "",
		speakerJob: "",
		date: "30 Mei 2026",
		time: "09.00 - 12.00 WIB",
		speakerPhoto: "",
	},
	{
		id: "083109",
		day: "Day 09",
		topic: "Thrive, Not Survive: Building a Sustainable Career Globally",
		speaker: "Mareda Fenty",
		speakerJob: "Spv HR & Organization Development @Harian Kompas",
		date: "06 Juni 2026",
		time: "09.00 - 12.00 WIB",
		speakerPhoto: "/Assets/Revamp/Speaker/Speaker-Black-and-White/Mareda-Fenty.png",
	},
];

export default schedule_data;